### ISSUE TITLE
Question: What is the use of '__$CODA$__'

### ISSUE THREAD

**Issue by KhaledElAnsari** [nolanlawson/substring-trie#1]
Hey, I just want to know what is the use of [`__$CODA$__`](https://github.com/nolanlawson/substring-trie/blob/master/index.js#L3) in this project. Thanks in advance

**Comment by nolanlawson** [comment]
It's to mark the end of a string from the dictionary.

**Comment by nolanlawson** [comment]
I can rename it to anything as long as it has two characters. Maybe then it would be less confusing. :)

**Comment by nolanlawson** [comment]
3b12311505a1a6216411da0caf9d9b2ba889e6d4

**Comment by KhaledElAnsari** [comment]
Oh I see! thanks Nolan
